<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<wsdl:definitions
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:s="http://www.w3.org/2001/XMLSchema" name="Contacts"
        targetNamespace="http://webservices.ilyachuvaev.com/Contacts/"
        xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:contacts="http://com/ilyachuvaev/webservices/contactservice"
        xmlns:tns="http://webservices.ilyachuvaev.com/Contacts/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >

    <wsdl:documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://schemas.xmlsoap.org/wsdl/ ">
        Contact Service
    </wsdl:documentation>

    <wsdl:types>
        <s:import namespace="http://com/ilyachuvaev/webservices/contactservice"
                  schemaLocation="ContactService.wsdl">
        </s:import>
    </wsdl:types>

    <wsdl:message name="ContactDetailsRequest">
        <wsdl:part element="contacts:ContactDetailsRequest" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="ContactDetailsResponse">
        <wsdl:part element="contacts:ContactDetailsResponse" name="parameters"/>
    </wsdl:message>

    <wsdl:portType name="Contacts">
        <wsdl:operation name="GetContactDetails">
            <wsdl:input message="tns:ContactDetailsRequest"/>
            <wsdl:output message="tns:ContactDetailsResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ContactServiceSoapBinding" type="tns:Contacts">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetContactDetails">
            <soap:operation soapAction="http://www.ilyachuvaev.com/Contacts/GetContactDetails"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ContactService">
        <wsdl:port binding="tns:ContactServiceSoapBinding" name="ContactsPort">
            <soap:address location="http://localhost:8080/services/contacts"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>